#!/usr/bin/env python
## ...........................................................................
## 
## PIMMS (Polymer Interactions in Multicomponent Mixtures)
## Alex Holehouse, Pappu Lab, Holehouse Lab 
## Copyright 2015 - 2020
## ...........................................................................

import sys
import argparse 
import os


# UNCOMMENT for kernprof
#sys.path.insert(0,'/Users/alex/Dropbox/WASHU/pappu/tools/PyLat')


from pimms.simulation import Simulation
from pimms.keyfile_parser import KeyFileParser
from pimms import keyfile_parser, IO_utils, CONFIG


import pimms 

def print_startup():
    IO_utils.status_message('','major')
    print("+-------------------------------------------------+")
    print("|                                                 |")
    print("|                      PIMMS                      |")
    print("|                                                 |")
    print("| Polymer Interactions in Multicomponent Mixtures |")
    print("|                                                 |")
    print("+-------------------------------------------------+")
    print("         Version [%s]" % (pimms.__version__))
    print("")
    IO_utils.status_message('STARTING PIMMS...','major')

def print_info_header():
    print_startup()
    
    IO_utils.stdout('[-i/--info] flag prints out information on every keyword that a PIMMS simulation can use. Flags are divided into those which are required for PIMMS to run, and those which modulate default behaviour. \n', 60)
    #IO_utils.stdout('This is not yet complete - sorry!\n', 60)


# because we want this to be a stand alone program we need to include all
# the argparse stuff inside a __main__ guard
if __name__=="__main__":

    # We create a argument parser (called 'parser') here 
    # Basically what this does is create an ArgumentParser object
    parser = argparse.ArgumentParser()

    # We add the command line argument(s) we expected to parse
    # I've only defined one here, but we can add as many as we want.
    #
    #
    # --file is the long name which the program uses
    # -f is the short name
    # help describes what this argument does

    parser.add_argument("-keyfile", "-k", help="Filename of keyfile") 
    parser.add_argument("--info", "-i", help="Prints a lot of keyfile options", nargs='?', const='LIST') 
    parser.add_argument("--version", "-v", help="Prints out the current version", action='store_true') 

    # having defined our argument variables we now parse the arguments parsed
    # to the program
    args = parser.parse_args()


    # if args has a variable called keyfile (which will happen if we passed
    # our program an argument associated with the -k or -keyfile flag
    if args.version:
        print('version %s' % (pimms.__version__))
        
    elif args.info is not None:
        print_info_header()
        
        multiline_leader='          '
        
        if args.info in CONFIG.KEYWORDS_DESCRIPTION:
            k = args.info
            k_type    = CONFIG.KEYWORDS_DESCRIPTION[k][0]
            k_desc    = CONFIG.KEYWORDS_DESCRIPTION[k][1]

            try:
                k_default = CONFIG.DEFAULTS[k]
            except KeyError:
                k_default = 'N/A'

                

            IO_utils.stdout('NAME    : %s' % (k), multiline_leader=multiline_leader)
            IO_utils.stdout('TYPE    : %s' % (k_type), multiline_leader=multiline_leader)
            IO_utils.stdout('DESCR   : %s' % (k_desc), multiline_leader=multiline_leader)
            IO_utils.stdout('DEFAULT : %s' % (k_default), multiline_leader=multiline_leader)
            IO_utils.newline()
        elif args.info == 'ALL':
            for k in CONFIG.KEYWORDS_DESCRIPTION:
                k_type = CONFIG.KEYWORDS_DESCRIPTION[k][0]
                k_desc = CONFIG.KEYWORDS_DESCRIPTION[k][1]

                
                try:
                    k_default = CONFIG.DEFAULTS[k]
                except KeyError:
                    k_default = 'N/A'
                
                
                IO_utils.stdout('NAME:     %s' % (k), multiline_leader=multiline_leader)
                IO_utils.stdout('TYPE:     %s' % (k_type), multiline_leader=multiline_leader)
                IO_utils.stdout('DESC:     %s' % (k_desc), multiline_leader=multiline_leader)
                IO_utils.stdout('DEFAULT : %s' % (k_default), multiline_leader=multiline_leader)
                IO_utils.newline()
        elif args.info == 'LIST':
            IO_utils.stdout('To get information on a specific keyword pass -i <keyword name>. Alternatively pass -i ALL to print every keyword info out.')
            print('')
            print('All valid keywords listed below:')
            print('--------------------------------------')
            s = ''
            for k in CONFIG.KEYWORDS_DESCRIPTION:
                s = s + " " + k
            IO_utils.stdout(s)
            print('')
            
                
            
        else:
            print('Unknown argument passed to -i/--info')
    
        
    elif args.keyfile:

        # print the standard startup message!
        print_startup()

        if not os.path.isfile(args.keyfile):
            IO_utils.status_message('Could not open file "%s". Exiting...\n' %(args.keyfile), msg_type='error')
            exit(1)
            
        # read in the keyfile
        KeyFile = KeyFileParser(args.keyfile)

        # print a summary
        KeyFile.print_summary()
        
        # Set up a new simulation
        Simulator = Simulation(KeyFile.keyword_lookup)

        # Run a new simulation
        Simulator.run_simulation()

    else:
        print('Pass all arguments (try --help for more info)')


