## ...........................................................................
## 
## PIMMS (Polymer Interactions in Multicomponent Mixtures)
## Author: Alex Holehouse
## Developed by the Holehouse and Pappu labs
## Copyright 2015 - 2026
## 
## ...........................................................................


import numpy as np
cimport numpy as cnp
cnp.import_array()

cimport cython 

from pimms import mega_crank


#from numpy cimport int16_t as NUMPY_INT16_TYPE
#ctypedef NUMPY_INT16_TYPE  NUMPY_INT_TYPE
#ctypedef cnp.int64_t NUMPY_INT_TYPE_long

from pimms.cython_config cimport NUMPY_INT_TYPE
from pimms.cython_config cimport NUMPY_INT_TYPE_long
from pimms.CONFIG import NP_INT_TYPE as NUMPY_INT_TYPE_PYTHON

# RNG is delegated to mega_crank (splitmix64); see mega_crank.seed_C_rand /
# randint_ext / accept_or_reject_ext.

## Define high performance local min and max functions...
##

cdef inline int int_max(int a, int b): return a if a >= b else b
cdef inline int int_min(int a, int b): return a if a <= b else b


#-----------------------------------------------------------------
# 
def update_position_2D(NUMPY_INT_TYPE[:] old_position, NUMPY_INT_TYPE[:,:]  grid, NUMPY_INT_TYPE x_off, NUMPY_INT_TYPE y_off, NUMPY_INT_TYPE XDIM, NUMPY_INT_TYPE YDIM):
    """
    2D counterpart of mega_crank.update_position: apply a per-axis offset to a
    position, wrap it back into the box, and reject the result if the target site
    is already occupied.

    Nothing is written to the grid here; this only proposes a position.

    Parameters
    ----------
    old_position : (2,) NUMPY_INT_TYPE (int32) memoryview
        Current (x, y) of the bead.
    grid : (XDIM, YDIM) NUMPY_INT_TYPE (int32) memoryview
        Occupancy grid, read to test for a hard-sphere clash. A site holds the
        chainID of whatever occupies it, and 0 when empty.
    x_off : NUMPY_INT_TYPE (int32)
        Displacement along x. Callers pass -1, 0 or +1.
    y_off : NUMPY_INT_TYPE (int32)
        Displacement along y.
    XDIM : NUMPY_INT_TYPE (int32)
        Box size along x, used to wrap the proposed coordinate.
    YDIM : NUMPY_INT_TYPE (int32)
        Box size along y.

    Returns
    -------
    (2,) numpy.ndarray, NUMPY_INT_TYPE (int32)
        The wrapped proposed position, or [-1, 0] if the target site is
        occupied. Callers test element 0 for a negative value.
    """
    
    cdef cnp.ndarray[NUMPY_INT_TYPE, ndim=1] new_position = np.zeros([2], dtype=NUMPY_INT_TYPE_PYTHON)

    cdef int local_x = pbc_correction(old_position[0] + x_off, XDIM)
    cdef int local_y = pbc_correction(old_position[1] + y_off, YDIM)

    if grid[local_x, local_y] > 0:
        # fail. Also zero the y slot so the buffer never carries a stale
        # coordinate from a previous iteration - this makes the reference
        # structurally identical to the fast kernel (which writes out[1] = 0),
        # so the downstream hardwall straddle test sees the same values in both.
        new_position[0] = -1
        new_position[1] = 0
    # hard sphere clash
    else:
        # success        
        new_position[0] = local_x
        new_position[1] = local_y

    return (new_position)


#-----------------------------------------------------------------
# 
def mega_crank_2D(NUMPY_INT_TYPE[:,:] grid, 
                  NUMPY_INT_TYPE[:,:] type_grid,                   
                  NUMPY_INT_TYPE_long[:,:] idx_to_bead,
                  NUMPY_INT_TYPE[:,:] interaction_table, 
                  NUMPY_INT_TYPE[:,:] LR_interaction_table, 
                  NUMPY_INT_TYPE[:,:] SLR_interaction_table, 
                  NUMPY_INT_TYPE[:,:,:,:,:]  angle_lookup,
                  long energy,
                  float invtemp,
                  int nsteps,
                  NUMPY_INT_TYPE_long[:] bead_selector,
                  int passed_seed,
                  int hardwall):
              
    """
    Some explanation is in order re: what the input variables here are

    grid - the main lattice grid

    type_grid - mirrors the lattice grid but the integers represent residue types not chain IDs

    interaction_table - lookup table for the short range interactions of 2 beads
    
    interaction_table - lookup table for the long range interactions of 2 beads

    angle_lookup - lookup table for angle energies 

    energy - current energy

    invtemp - current inverse temperature

    nsteps - number of steps to perform

    passed_seed - a random seed generated by the main program, ensures reproducibility

    Parameters
    ----------
    grid : (XDIM, YDIM) NUMPY_INT_TYPE (int32) memoryview
        Occupancy grid holding the chainID at each occupied site and 0 where
        empty. Updated in place as moves are accepted.
    type_grid : (XDIM, YDIM) NUMPY_INT_TYPE (int32) memoryview
        Residue intcode at each occupied site, 0 for solvent. Updated in place
        alongside grid.
    idx_to_bead : (num_beads, 7) NUMPY_INT_TYPE_long (int64) memoryview
        Per-bead state table, laid out as in mega_crank.mega_crank but without
        the z column: 0 bead_flag, 1 LR flag, 2 intcode, 3 skip-angles flag,
        4 chainID, 5 x position, 6 y position. Columns 5 and 6 are updated in
        place as moves are accepted.
    interaction_table : (n_types, n_types) NUMPY_INT_TYPE (int32) memoryview
        Short-range pair energies indexed by the two residue intcodes, with row
        and column 0 holding the solvent interactions.
    LR_interaction_table : (n_types, n_types) NUMPY_INT_TYPE (int32) memoryview
        Long-range pair energies, same indexing.
    SLR_interaction_table : (n_types, n_types) NUMPY_INT_TYPE (int32) memoryview
        Super-long-range pair energies, same indexing.
    angle_lookup : (n_types, 3, 3, 3, 3) NUMPY_INT_TYPE (int32) memoryview
        Precomputed angle penalties indexed by the middle bead's intcode and the
        two unit bond vectors, each component shifted from -1/0/+1 into 0/1/2.
    energy : long
        Total system energy on entry. Carried through the sweep and returned.
    invtemp : float (C float)
        Inverse temperature (1 / kT) used in the Metropolis criterion.
    nsteps : int (C int)
        Number of single-bead moves to attempt. A value <= 0 is a no-op.
    bead_selector : (>= nsteps,) NUMPY_INT_TYPE_long (int64) memoryview
        Pre-drawn bead indices, one per substep, indexed by the loop counter.
    passed_seed : int (C int)
        Seed for the PRNG, which lives in mega_crank and is shared with the 3D
        kernel. Set once at the start of the sweep.
    hardwall : int (C int)
        1 if the box has hard walls, in which case any proposal whose bond would
        straddle the boundary is discarded and interactions across the boundary
        are treated as solvent; 0 for fully periodic.

    Returns
    -------
    tuple of (long, int)
        (energy, accepted_moves) - the total system energy after the sweep and
        the number of proposals accepted.
    """
    # set randomseed (shared splitmix64 state lives in mega_crank)
    mega_crank.seed_C_rand(passed_seed)
    # a non-positive substep count is a no-op; without this guard a negative
    # nsteps compared against an unsigned loop counter would wrap to ~2^32
    # iterations and read bead_selector far out of bounds
    if nsteps <= 0:
        return (energy, 0)

    
    cdef int i, bead_index;
    cdef int accepted_moves;
    cdef int XDIM, YDIM;
    cdef int num_beads;
    cdef int bead_flag, move_success
    cdef int old_x, old_y
    cdef int lr_vs_sr, bead_id
    cdef long delta_energy, delta_angle_energy

    accepted_moves = 0

    cdef cnp.ndarray[NUMPY_INT_TYPE, ndim=2] position_triptic = np.zeros([3, 2], dtype=NUMPY_INT_TYPE_PYTHON)    
    cdef cnp.ndarray[NUMPY_INT_TYPE, ndim=2] three_position_holder = np.zeros([3, 2], dtype=NUMPY_INT_TYPE_PYTHON)    
    cdef cnp.ndarray[NUMPY_INT_TYPE, ndim=2] two_position_holder = np.zeros([2, 2], dtype=NUMPY_INT_TYPE_PYTHON)
    
    cdef cnp.ndarray[NUMPY_INT_TYPE, ndim=1] old_position = np.zeros([2], dtype = NUMPY_INT_TYPE_PYTHON)
    cdef cnp.ndarray[NUMPY_INT_TYPE, ndim=1] anchor_bead = np.zeros([2], dtype = NUMPY_INT_TYPE_PYTHON)    
    cdef cnp.ndarray[NUMPY_INT_TYPE, ndim=1] new_position = np.zeros([2], dtype = NUMPY_INT_TYPE_PYTHON)
    

    XDIM = grid.shape[0]
    YDIM = grid.shape[1]

    # get the number of beads
    
    # angle short-circuit
    for i in range(nsteps):

        # select random a bead from the preallocated bead_selector      
        bead_index   = bead_selector[i]

        # get position
        bead_flag = idx_to_bead[bead_index,0]
        old_x = idx_to_bead[bead_index,5]
        old_y = idx_to_bead[bead_index,6]
        lr_vs_sr = idx_to_bead[bead_index,1]
        bead_id = idx_to_bead[bead_index,4]

        old_position[0] = old_x
        old_position[1] = old_y

        # ------------------------------------------------------------
        # if single bead (beadflag == 0)
        if bead_flag == 0:
            move_success = single_bead_crank_2D(old_position, grid, XDIM, YDIM, new_position)

            # HARDWALL monomer guard - see the 3D reference kernel (mega_crank.pyx)
            if hardwall == 1 and move_success == 1:
                two_position_holder[0] = new_position
                two_position_holder[1] = old_position
                if do_positions_stradle_pbc_boundary_2D(two_position_holder, 2) == 1:
                    continue

        # ------------------------------------------------------------
        # if N-terminal bead (beadflag == 1)
        elif bead_flag == 1:
            anchor_bead[0] = idx_to_bead[bead_index+1,5]
            anchor_bead[1] = idx_to_bead[bead_index+1,6]

            move_success = single_bead_crank_2D(anchor_bead, grid, XDIM, YDIM, new_position)
            
            if hardwall == 1:
                two_position_holder[0] = new_position
                two_position_holder[1] = anchor_bead
                if do_positions_stradle_pbc_boundary_2D(two_position_holder, 2) == 1:
                    continue

        # ------------------------------------------------------------
        # if C-terminal bead (beadflag == 3)
        elif bead_flag == 3:

            anchor_bead[0] = idx_to_bead[bead_index-1,5]
            anchor_bead[1] = idx_to_bead[bead_index-1,6]
            move_success = single_bead_crank_2D(anchor_bead, grid, XDIM, YDIM, new_position)

            if hardwall == 1:
                two_position_holder[0] = anchor_bead
                two_position_holder[1] = new_position

                if do_positions_stradle_pbc_boundary_2D(two_position_holder,2) == 1:
                    continue

        # ------------------------------------------------------------
        # we're somewhere inside the chain, and beadflag is 2,4,5, or 6
        else:
            position_triptic[0,0] = idx_to_bead[bead_index-1,5]
            position_triptic[0,1] = idx_to_bead[bead_index-1,6]
            
            position_triptic[1,0] = old_x
            position_triptic[1,1] = old_y

            position_triptic[2,0] = idx_to_bead[bead_index+1,5]
            position_triptic[2,1] = idx_to_bead[bead_index+1,6]


            
            # normal crank move!
            move_success = crank_it_2D(position_triptic, grid, XDIM, YDIM, new_position)

            if hardwall == 1:
                three_position_holder[0] = position_triptic[0]
                three_position_holder[1] = new_position
                three_position_holder[2] = position_triptic[2]
                
                if do_positions_stradle_pbc_boundary_2D(three_position_holder,3) == 1:
                    continue
        
        # if hardsphere success
        if move_success == 1:

            delta_energy = get_energy_change_2D(grid, type_grid, old_position, new_position, lr_vs_sr,  interaction_table, LR_interaction_table, SLR_interaction_table, XDIM, YDIM, hardwall)
            delta_angle_energy = get_angle_energy_change_2D(bead_index, idx_to_bead, new_position, angle_lookup)
            
            if mega_crank.accept_or_reject_ext(invtemp, energy, energy+delta_energy+delta_angle_energy) == 1:
                                
                # delete from main grid and insert into new position                                            
                grid[old_x, old_y] = 0

                # inert the bead to its new position
                grid[new_position[0], new_position[1]] = bead_id
                
                # set new type grid to old type grid value
                type_grid[new_position[0], new_position[1]] = type_grid[old_x, old_y]

                # zero out old position on type grid                
                type_grid[old_x, old_y] = 0

                # IMPORTANT!!! This change *MUST* be done last as the old_position is actually a reference
                # to chain_position[bead_index] so changing it BEFORE hand changes the old_position variable and
                # breaks everything
                idx_to_bead[bead_index,5] = new_position[0]
                idx_to_bead[bead_index,6] = new_position[1]
                
                
                energy = energy + delta_energy + delta_angle_energy
                accepted_moves = accepted_moves + 1
                

    return (energy, accepted_moves)



# --------------------------------------------------------------------------------------------------------
#
# 
cdef int crank_it_2D(NUMPY_INT_TYPE[:,:] position_triptic,
                     NUMPY_INT_TYPE[:,:] grid,
                     int XDIM,
                     int YDIM,
                     NUMPY_INT_TYPE[:] new_position):
    """
    Perform crankshaft move!

    2D counterpart of mega_crank.crank_it. The i-1 and i+1 positions constrain
    where the middle bead can go: both are first lifted out of periodic space (a
    separation of more than 2 along an axis can only mean the pair straddles a
    boundary), the allowed box is intersected there, and the drawn position is
    wrapped back into the box.

    Unlike the 3D version this writes through an output memoryview rather than
    allocating, and reports success through the return value.

    Parameters
    ----------
    position_triptic : (3, 2) NUMPY_INT_TYPE (int32) memoryview
        The x,y positions of the -1, 0 and 1 positions of the chain, one per
        row, where row 1 is the bead to be moved and rows 0 and 2 are the
        flanking beads that constrain it.
    grid : (XDIM, YDIM) NUMPY_INT_TYPE (int32) memoryview
        Occupancy grid, read to reject hard-sphere clashes.
    XDIM : int (C int)
        Box size along x.
    YDIM : int (C int)
        Box size along y.
    new_position : (2,) NUMPY_INT_TYPE (int32) memoryview
        Output buffer. Written with the wrapped proposed position on success,
        and with [-1, 0] on failure.

    Returns
    -------
    int (C int)
        1 if a position was proposed, 0 if the target site was occupied.
    """
   
    cdef int N_side_x, N_side_y, C_side_x, C_side_y;
    cdef int x_min, x_max, y_min, y_max
    # extract out x and y positions and perform a series of PBC corrections as needed
    N_side_x = position_triptic[0,0]
    N_side_y = position_triptic[0,1]

    C_side_x = position_triptic[2,0]
    C_side_y = position_triptic[2,1]

    ## Periodicity fix 1
    # move into a non-periodic space just for now
    if abs(N_side_x - C_side_x) > 2:
        if N_side_x > C_side_x:
            C_side_x = C_side_x + XDIM
        else:
            N_side_x = N_side_x + XDIM
        
    if abs(N_side_y - C_side_y) > 2:
        if N_side_y > C_side_y:
            C_side_y = C_side_y + YDIM
        else:
            N_side_y = N_side_y + YDIM

    # get smallest/largest possible new x value
    x_min = int_max(N_side_x-1, C_side_x-1) 
    x_max = int_min(N_side_x+1, C_side_x+1) 

    # get smallest/largest possible new y value
    y_min = int_max(N_side_y-1, C_side_y-1) 
    y_max = int_min(N_side_y+1, C_side_y+1) 
    
    cdef int local_x = pbc_correction((x_min + mega_crank.randint_ext(1, (x_max - x_min + 1)) - 1 ) , XDIM);
    cdef int local_y = pbc_correction((y_min + mega_crank.randint_ext(1, (y_max - y_min + 1)) - 1 ) , YDIM)
    
    if grid[local_x, local_y] > 0:
        # fail (y zeroed to match the fast kernel structurally - see above)
        new_position[0] = -1
        new_position[1] = 0
        return 0

    # hard sphere clash
    else:
        # success        
        new_position[0] = local_x;
        new_position[1] = local_y;
        return 1

# --------------------------------------------------------------------------------------------------------
#
# 
@cython.wraparound(False)
@cython.boundscheck(False)
cdef int single_bead_crank_2D(NUMPY_INT_TYPE[:] old_position,
                              NUMPY_INT_TYPE[:,:] grid,
                              int XDIM,
                              int YDIM,
                              NUMPY_INT_TYPE[:] new_position):
    """
    Perform crankshaft move!

    Single beads are easy as the new position is just a random perturbation in
    both coordinates. For a terminal bead the caller passes the bonded anchor's
    position instead, so the proposal lands within one site of it.

    Parameters
    ----------
    old_position : (2,) NUMPY_INT_TYPE (int32) memoryview
        Position the perturbation is applied to.
    grid : (XDIM, YDIM) NUMPY_INT_TYPE (int32) memoryview
        Occupancy grid, read to reject hard-sphere clashes.
    XDIM : int (C int)
        Box size along x.
    YDIM : int (C int)
        Box size along y.
    new_position : (2,) NUMPY_INT_TYPE (int32) memoryview
        Output buffer. Written with the wrapped proposed position on success,
        and with [-1, 0] on failure.

    Returns
    -------
    int (C int)
        1 if a position was proposed, 0 if the target site was occupied.
    """

    cdef int x_off, y_off;

    x_off = (mega_crank.randint_ext(0,2)-1)
    y_off = (mega_crank.randint_ext(0,2)-1)


    cdef int local_x = pbc_correction(old_position[0] + x_off, XDIM)
    cdef int local_y = pbc_correction(old_position[1] + y_off, YDIM)

    #if grid[new_position[0], new_position[1], new_position[2]] > 0:
    if grid[local_x, local_y] > 0:
        # fail (y zeroed to match the fast kernel structurally - see above)
        new_position[0] = -1
        new_position[1] = 0
        return 0

    # hard sphere clash
    else:
        # success        
        new_position[0] = local_x
        new_position[1] = local_y
        return 1


@cython.wraparound(False)
@cython.boundscheck(False)
cdef long get_angle_energy_change_2D(int bead_index,
                                     NUMPY_INT_TYPE_long[:,:] idx_to_bead, 
                                     NUMPY_INT_TYPE[:] new_position, 
                                     NUMPY_INT_TYPE[:,:,:,:,:,] angle_lookup):
                        
    """
    Function that takes a pre-computed angle energy lookup table and returns the change
    in angle energy before and after the move, where the move must be moving a single bead. 
    Note this function is almost purely C (as measured by the output from cython -a)

    Only the angles that actually involve the moved bead are touched: the bead
    flag in column 0 of idx_to_bead selects a window of up to five consecutive
    beads around it, and the penalty is summed over that window before and after
    the move. Beads flagged to skip angles return 0 immediately.

    Parameters
    ----------
    bead_index : int (C int)
        Row of idx_to_bead for the specific bead of interest.

    idx_to_bead : (num_beads, 7) NUMPY_INT_TYPE_long (int64) memoryview
        Full matrix containing the complete system information (see the description in
        the mega_crank function description for a full summary of this variable).
        Read only here; the caller commits the move afterwards.

    new_position : (2,) NUMPY_INT_TYPE (int32) memoryview
        The [x, y] position that the moved bead is moving to.

    angle_lookup : (n_types, 3, 3, 3, 3) NUMPY_INT_TYPE (int32) memoryview
        Lookup table that translates the two unit bond vectors into an angle
        energy penalty based on precomputed values, indexed by the middle bead's
        intcode followed by the four vector components shifted from -1/0/+1 into
        0/1/2.

    Returns
    -------
    long
        New angle penalty minus old angle penalty over the affected window. 0 if
        the bead is flagged to skip angles.
    """

    # if the skip angle is set to true
    if idx_to_bead[bead_index,3] == 1:
        return 0

    # initialize a bunch of values
    cdef long angle_penalty_new = 0;
    cdef long angle_penalty_old = 0;

    cdef cnp.ndarray[NUMPY_INT_TYPE, ndim=2] angle_positions  = np.zeros([5, 2], dtype=NUMPY_INT_TYPE_PYTHON)    
    cdef cnp.ndarray[NUMPY_INT_TYPE, ndim=1] intcode_lookup = np.zeros([5], dtype=NUMPY_INT_TYPE_PYTHON)    
    cdef int offset, offset_start, offset_end;
    cdef int i;
    cdef int angle_idx, local_move_idx;
    cdef int a0, a1, b0, b1
    cdef int bead_flag

    offset_start = 0
    offset_end = 0
    bead_flag = idx_to_bead[bead_index,0]

    # N-terminal bead
    if bead_flag == 1:
        offset_start = 0
        offset_end   = 3

    # central bead
    elif bead_flag == 2:
        offset_start = -2
        offset_end   = 3

    # central bead in an OXO configuration
    elif bead_flag == 4:
        offset_start = -1
        offset_end   = 2


    # C terminal bead
    elif bead_flag == 3:
        offset_start = -2
        offset_end   = 1

    # N terminal bead +1 from start
    elif bead_flag == 5:
        offset_start = -1
        offset_end   = 3

    # C terminal bead -1 from end
    elif bead_flag == 6:
        offset_start = -2
        offset_end   = 2


    # this is the index we use to keep track of the dynamic angle_positions array
    angle_idx = 0

    local_move_idx  = -1
    angle_idx = 0

    for offset in range(offset_start, offset_end):
        pos = bead_index + offset

        angle_positions[angle_idx, 0] = idx_to_bead[pos,5] # x pos
        angle_positions[angle_idx, 1] = idx_to_bead[pos,6] # y pos
        intcode_lookup[angle_idx]     = idx_to_bead[pos,2] # intcode

        if pos == bead_index:
            local_move_idx = angle_idx

        angle_idx = angle_idx + 1


    for i in range(0, angle_idx-2):

        # compute the two vectors between the positions
        a0 = fix_angle_pbc_issues(angle_positions[i+1, 0] - angle_positions[i, 0])
        a1 = fix_angle_pbc_issues(angle_positions[i+1, 1] - angle_positions[i, 1])

        b0 = fix_angle_pbc_issues(angle_positions[i+1, 0] - angle_positions[i+2, 0])
        b1 = fix_angle_pbc_issues(angle_positions[i+1, 1] - angle_positions[i+2, 1])

        angle_penalty_old = angle_lookup[intcode_lookup[i+1], a0+1, a1+1, b0+1, b1+1] + angle_penalty_old

    # same guard as the fast kernel: local_move_idx can stay -1 on the defensive
    # unknown-flag path, and a [-1] write under wraparound(False) is out of bounds
    if local_move_idx >= 0:
        angle_positions[local_move_idx,0] = new_position[0]
        angle_positions[local_move_idx,1] = new_position[1]

    for i in range(0, angle_idx-2):

        # compute the two vectors between the positions
        a0 = fix_angle_pbc_issues(angle_positions[i+1, 0] - angle_positions[i, 0])
        a1 = fix_angle_pbc_issues(angle_positions[i+1, 1] - angle_positions[i, 1])

        b0 = fix_angle_pbc_issues(angle_positions[i+1, 0] - angle_positions[i+2, 0])
        b1 = fix_angle_pbc_issues(angle_positions[i+1, 1] - angle_positions[i+2, 1])

        angle_penalty_new = angle_lookup[intcode_lookup[i+1], a0+1, a1+1, b0+1, b1+1] + angle_penalty_new
        
    return (angle_penalty_new - angle_penalty_old)    


@cython.cdivision(True)
cdef int fix_angle_pbc_issues(int distance):
    """
    Hack that takes advantage of the fact that the distances all must be -1,0, +1 and 
    we're always computing a X->O vector where O is the bend point

    A bonded pair that straddles the boundary shows up as a raw separation of
    +/- (DIM - 1), so anything outside [-1, 1] is folded back to the unit step of
    the opposite sign.

    Parameters
    ----------
    distance : int (C int)
        Raw per-axis separation between two bonded beads, taken straight from
        their stored coordinates without any PBC correction.

    Returns
    -------
    int (C int)
        The true unit step: -1, 0 or +1.
    """
    if distance < -1:
        return 1
    elif distance > 1:
        return -1
    else:
        return distance
    

# these directives made the function slower...
#@cython.wraparound(False)
#@cython.boundscheck(False)
def get_energy_change_2D(NUMPY_INT_TYPE[:,:] grid, 
                         NUMPY_INT_TYPE[:,:] type_grid,
                         NUMPY_INT_TYPE[:] old_position,
                         NUMPY_INT_TYPE[:] new_position,
                         int LR_vs_SR, 
                         NUMPY_INT_TYPE[:,:] interaction_table, 
                         NUMPY_INT_TYPE[:,:] LR_interaction_table,
                         NUMPY_INT_TYPE[:,:] SLR_interaction_table,
                         int XDIM, 
                         int YDIM,
                         int hardwall):
                         
    """
    2D counterpart of mega_crank.get_energy_change: the non-bonded energy change
    for moving one bead from old_position to new_position.

    Four sums are accumulated: the bead's interactions at its current site, the
    solvent interactions the current site would have once the bead leaves, and
    the same two at the destination. The returned delta is
    (energy_new + energy_old_empty) - (energy_old + energy_new_empty), so the
    interactions the vacated and filled sites make with the rest of the system
    are counted exactly once each.

    type_grid is temporarily edited to place the bead at the destination while
    the new-site sums are taken, and restored before returning, so the caller
    sees it unchanged.

    Parameters
    ----------
    grid : (XDIM, YDIM) NUMPY_INT_TYPE (int32) memoryview
        Occupancy grid. Present for signature compatibility with the callers;
        the energy is read entirely from type_grid.

    type_grid : (XDIM, YDIM) NUMPY_INT_TYPE (int32) memoryview
        Residue intcode at each occupied site, 0 for solvent. Edited and
        restored in place, as described above.

    old_position : (2,) NUMPY_INT_TYPE (int32) memoryview
        The [x, y] the bead is moving from.

    new_position : (2,) NUMPY_INT_TYPE (int32) memoryview
        The [x, y] the bead is moving to.

    LR_vs_SR : int (C int)
        1 if this bead engages in long-range interactions, in which case the 7x7
        neighbourhood is swept and split into SR, LR and SLR shells; 0 to sweep
        only the 3x3 short-range neighbourhood.

    interaction_table : (n_types, n_types) NUMPY_INT_TYPE (int32) memoryview
        Short-range pair energies indexed by the two residue intcodes, with row
        and column 0 holding the solvent interactions.

    LR_interaction_table : (n_types, n_types) NUMPY_INT_TYPE (int32) memoryview
        Long-range pair energies, same indexing. Only read when LR_vs_SR is 1.

    SLR_interaction_table : (n_types, n_types) NUMPY_INT_TYPE (int32) memoryview
        Super-long-range pair energies, same indexing. Only read when LR_vs_SR
        is 1.

    XDIM : int (C int)
        Box size along x, used to wrap the neighbourhood sweep.

    YDIM : int (C int)
        Box size along y.

    hardwall : int (C int)
        1 if the box has hard walls, in which case a short-range partner across
        the boundary is treated as solvent and an LR/SLR partner across the
        boundary is skipped entirely; 0 for fully periodic.

    Returns
    -------
    long
        The change in non-bonded energy for the proposed move.
    """

    # We define four energy variables which are going to be used to calcualte
    # the DELTA energy. 
    #
    # --> energy old is the interactions between the bead and its
    # partners in its current location
    #
    # --> energy_old_empy is the energy associated with the site after this
    # bead has been removed (i.e. solvent to local partners only)
    #
    # --> energy_new is the interaction between the bead and its partners in
    #     its NEW location!
    #
    # --> energy_new_empty is the interaction between the bead and its 
    
    cdef long energy_old       = 0
    cdef long energy_old_empty = 0
    cdef long energy_new       = 0
    cdef long energy_new_empty = 0 
    

    cdef int old_x, old_y;
    cdef int new_x, new_y;
    cdef int tmp_x, tmp_y;

    cdef int x, y

    cdef unsigned int site_bead_type, bead_type;

    # extract 
    new_x = new_position[0]
    new_y = new_position[1]

    old_x = old_position[0]
    old_y = old_position[1]

    # get the type of the current beads
    bead_type = type_grid[old_x, old_y]
    
    ## ************************************************************************************************
    ##  Long range energy
    ##
    # if we're looking at a bead which engages in longrange interactions 
    if LR_vs_SR == 1:

        ## First evaluate the old energy        
        for x in range(-3,4):
            for y in range(-3,4):
                tmp_x = pbc_correction(old_x + x, XDIM)
                tmp_y = pbc_correction(old_y + y, YDIM)

                site_bead_type = type_grid[tmp_x, tmp_y]

                # short-range interactions
                if abs(x) < 2 and abs(y) < 2:
                    
                    # if harwall boundary is on then short range interaction between a bead and something across
                    # the boundary is by definition bead-solvent interaction (type 0)
                    if hardwall == 1:
                        if abs(tmp_x - old_x) > 3 or abs(tmp_y - old_y) > 3:
                            site_bead_type = 0                
                        
                    # bead-site interaction                 
                    energy_old = energy_old + interaction_table[bead_type, site_bead_type]

                    # might be faster to just read this from memory every time - is if or a memory read and addition faster?
                    if site_bead_type > 0:
                        energy_old_empty = energy_old_empty + interaction_table[0, site_bead_type]

                # long range interactions (maybe optimize this in future...) - note long range interactions cannot
                # contribute to the energy_old_empty variable
                elif abs(x) < 3 and abs(y) < 3:                

                    # if harwall boundary is on - don't feel LR or SLR interactions over boundary
                    if hardwall == 1:
                        if abs(tmp_x - old_x) > 3 or abs(tmp_y - old_y) > 3:
                            continue
                    energy_old = energy_old + LR_interaction_table[bead_type, site_bead_type]

                else:
                    # if harwall boundary is on - don't feel LR or SLR interactions over boundary
                    if hardwall == 1:
                        if abs(tmp_x - old_x) > 3 or abs(tmp_y - old_y) > 3:
                            continue
                    energy_old = energy_old + SLR_interaction_table[bead_type, site_bead_type]
                    

        # reset the typegrid to the new configuation
        type_grid[new_x,new_y] = type_grid[old_x,old_y]
        type_grid[old_x,old_y] = 0

        ## then evaluate the new energy        
        for x in range(-3,4):
            for y in range(-3,4):

                # get PBC corrected positions of interest
                tmp_x = pbc_correction(new_x + x, XDIM)
                tmp_y = pbc_correction(new_y + y, YDIM)

                site_bead_type = type_grid[tmp_x, tmp_y]
                    
                # short-range interactions
                if abs(x) < 2 and abs(y) < 2:

                    if hardwall == 1:
                        if abs(tmp_x - new_x) > 3 or abs(tmp_y - new_y) > 3:
                            site_bead_type = 0                
                        
                    # bead-site interaction                 
                    energy_new = energy_new + interaction_table[bead_type, site_bead_type]
                    
                    if site_bead_type > 0:
                        energy_new_empty = energy_new_empty + interaction_table[0, site_bead_type]
                
                # long range interactions (maybe optimize this in future...) - note long range interactions cannot
                # contribute to the energy_old_empty variable

                # long range interactions (maybe optimize this in future...) - note long range interactions cannot
                # contribute to the energy_old_empty variable
                elif abs(x) < 3 and abs(y) < 3:              
                    # if harwall boundary is on - don't feel LR or SLR interactions over boundary
                    if hardwall == 1:
                        if abs(tmp_x - new_x) > 3 or abs(tmp_y - new_y) > 3:
                            continue  

                    energy_new = energy_new + LR_interaction_table[bead_type, site_bead_type]

                else:
                    # if harwall boundary is on - don't feel LR or SLR interactions over boundary
                    if hardwall == 1:
                        if abs(tmp_x - new_x) > 3 or abs(tmp_y - new_y) > 3:
                            continue  

                    energy_new = energy_new + SLR_interaction_table[bead_type, site_bead_type]


    ## ************************************************************************************************
    ##  only short range brah!
    ##
    else:
        for x in range(-1,2):
            for y in range(-1,2):

                # get PBC corrected positions of interest
                tmp_x = pbc_correction(old_x + x, XDIM)
                tmp_y = pbc_correction(old_y + y, YDIM)

                site_bead_type = type_grid[tmp_x, tmp_y]

                # if harwall boundary is on then overwrite site_bead_type
                if hardwall == 1:
                    if abs(tmp_x - old_x) > 3 or abs(tmp_y - old_y) > 3:
                        site_bead_type = 0                
                                                                 
                # bead-site interaction                 
                energy_old = energy_old + interaction_table[bead_type, site_bead_type]

                # might be faster to just read this from memory every time - is if or a memory read and addition faster?
                if site_bead_type > 0:
                    energy_old_empty = energy_old_empty + interaction_table[0, site_bead_type]
            
        # reset the typegrid to the new configuation
        type_grid[new_x,new_y] = type_grid[old_x,old_y]
        type_grid[old_x,old_y] = 0
                
        for x in range(-1,2):
            for y in range(-1,2):
                    
                # get PBC corrected positions of interest
                tmp_x = pbc_correction(new_x + x, XDIM)
                tmp_y = pbc_correction(new_y + y, YDIM)

                site_bead_type = type_grid[tmp_x, tmp_y]

                # if harwall boundary is on then overwrite site_bead_type
                if hardwall == 1:
                    if abs(tmp_x - new_x) > 3 or abs(tmp_y - new_y) > 3:
                        site_bead_type = 0                
                    
                # bead-site interaction                 
                energy_new = energy_new + interaction_table[bead_type, site_bead_type]

                # might be faster to just read this from memory every time - is if or a memory read and addition faster?
                if site_bead_type > 0:
                    energy_new_empty = energy_new_empty + interaction_table[0, site_bead_type]
                                                
    # finally correct for the self-self interactions we cover when x == y == 0
    energy_old_empty = energy_old_empty - interaction_table[0, bead_type]
    energy_old       = energy_old - interaction_table[bead_type, bead_type]
    energy_new_empty = energy_new_empty - interaction_table[0, bead_type]
    energy_new       = energy_new - interaction_table[bead_type, bead_type]

    # reset the type grid again...
    type_grid[old_x,old_y] = type_grid[new_x,new_y] 
    type_grid[new_x,new_y] = 0

    return (energy_new + energy_old_empty) - (energy_old + energy_new_empty)



@cython.cdivision(True)
cdef int pbc_correction(int value, int DIM):    
    """
    Performs intelligent periodic boundary correction
    which FIRST checks to see if we have a negative
    value and IF NOT uses the % operator - this means
    we can use % without checking the sign giving
    a 35% speedup per call

    The negative branch adds a single box length rather than taking a modulo, so
    it is only correct for value >= -DIM. That holds throughout this module,
    where value is always an in-box coordinate offset by at most 3 sites.

    Parameters
    ----------
    value : int (C int)
        Candidate coordinate along one axis, i.e. an in-box coordinate plus a
        small neighbour offset.
    DIM : int (C int)
        Box size along that axis.

    Returns
    -------
    int (C int)
        The coordinate wrapped back into [0, DIM).
    """
                            
    if value < 0:
        return DIM+value
    else:
        return (value % DIM)


@cython.wraparound(False)
@cython.boundscheck(False)
cdef int do_positions_stradle_pbc_boundary_2D(NUMPY_INT_TYPE[:,:] chain_positions, int chain_length):
    """                                       
    For a set of positions returns true if the positions straddle a boundary
    else return false

    Consecutive rows are bonded, so a per-axis separation greater than 1 can only
    mean the bond wraps the box. Under hard walls that is an illegal bond, and
    the caller discards the proposal.

    Parameters
    ----------
    chain_positions : (>= chain_length, 2) NUMPY_INT_TYPE (int32) memoryview
        Consecutive bonded positions to test. Callers reuse a fixed-size scratch
        buffer, so only the first chain_length rows are read.
    chain_length : int (C int)
        Number of rows to test, i.e. chain_length - 1 bonds.

    Returns
    -------
    int (C int)
        1 if any bond straddles the boundary, 0 otherwise.
    """

    cdef int pidx
    cdef int p1_x, p2_x, p1_y, p2_y
    
    

    for pidx in range(0, chain_length-1):
        p1_x = chain_positions[pidx,0]
        p2_x = chain_positions[pidx+1,0]

        p1_y = chain_positions[pidx,1]
        p2_y = chain_positions[pidx+1,1]
        
        if abs(p1_x - p2_x) > 1:
            return 1

        if abs(p1_y - p2_y) > 1:
            return 1

    return 0

