## ...........................................................................
## 
## PIMMS (Polymer Interactions in Multicomponent Mixtures)
## Author: Alex Holehouse
## Developed by the Holehouse and Pappu labs
## Copyright 2015 - 2020
## 
## ...........................................................................


import numpy as np
cimport numpy as cnp
cnp.import_array()

cimport cython 
import random

from pimms import mega_crank

ctypedef cnp.int64_t NUMPY_INT_TYPE

from libc.stdlib cimport rand, srand

## Define high performance local min and max functions...
##

cdef inline int int_max(int a, int b): return a if a >= b else b
cdef inline int int_min(int a, int b): return a if a <= b else b


#-----------------------------------------------------------------
# 
def update_position_2D(cnp.ndarray[NUMPY_INT_TYPE, ndim=1] old_position, cnp.ndarray[NUMPY_INT_TYPE, ndim=2] grid, int x_off, int y_off, int XDIM, int YDIM):
    
    cdef cnp.ndarray[NUMPY_INT_TYPE, ndim=1] new_position = np.zeros([2], dtype=int)

    cdef int local_x = pbc_correction(old_position[0] + x_off, XDIM)
    cdef int local_y = pbc_correction(old_position[1] + y_off, YDIM)

    if grid[local_x, local_y] > 0:
        # fail
        new_position[0] = -1
    # hard sphere clash
    else:
        # success        
        new_position[0] = local_x
        new_position[1] = local_y

    return (new_position)


#-----------------------------------------------------------------
# 
def mega_crank_2D(cnp.ndarray[NUMPY_INT_TYPE, ndim=2] grid, 
                  cnp.ndarray[NUMPY_INT_TYPE, ndim=2] type_grid,                   
                  cnp.ndarray[NUMPY_INT_TYPE, ndim=2] idx_to_bead,
                  cnp.ndarray[long, ndim=2] interaction_table, 
                  cnp.ndarray[long, ndim=2] LR_interaction_table, 
                  cnp.ndarray[long, ndim=2] SLR_interaction_table, 
                  cnp.ndarray[long, ndim=5] angle_lookup,
                  long energy,
                  float invtemp,
                  int nsteps,
                  cnp.ndarray[NUMPY_INT_TYPE, ndim=1] bead_selector,
                  int passed_seed,
                  int hardwall):
              
    """
    Some explanation is in order re: what the input variables here are

    grid - the main lattice grid

    type_grid - mirrors the lattice grid but the integers represent residue types not chain IDs

    interaction_table - lookup table for the short range interactions of 2 beads
    
    interaction_table - lookup table for the long range interactions of 2 beads

    angle_lookup - lookup table for angle energies 

    energy - current energy

    invtemp - current inverse temperature

    nsteps - number of steps to perform

    passed_seeed - a random seed generated by the main program, ensures reproducibility


    """
    # set randomseed
    srand(passed_seed)

    cdef int i, bead_index;
    cdef int accepted_moves;
    cdef int XDIM, YDIM;
    cdef int num_beads;

    accepted_moves = 0

    cdef cnp.ndarray[NUMPY_INT_TYPE, ndim=2] position_triptic = np.zeros([3, 2], dtype=int)    
    cdef cnp.ndarray[NUMPY_INT_TYPE, ndim=2] three_position_holder = np.zeros([3, 2], dtype=int)    
    cdef cnp.ndarray[NUMPY_INT_TYPE, ndim=2] two_position_holder = np.zeros([2, 2], dtype=int)    

    cdef cnp.ndarray[NUMPY_INT_TYPE, ndim=1] old_position;
    cdef cnp.ndarray[NUMPY_INT_TYPE, ndim=1] anchor_bead;
    cdef cnp.ndarray[NUMPY_INT_TYPE, ndim=1] new_position;

    XDIM = grid.shape[0]
    YDIM = grid.shape[1]

    # get the number of beads
    num_beads = len(idx_to_bead)
    
    # angle short-circuit
    for i in range(nsteps):

        # select random a bead from the preallocated bead_selector      
        bead_index   = bead_selector[i]
        print(bead_index)

        # get position
        old_position = idx_to_bead[bead_index][5:7]
        print(old_position)


        # ------------------------------------------------------------
        # if single bead (beadflag == 0)
        if idx_to_bead[bead_index][0] == 0:
            new_position = single_bead_crank_2D(old_position, grid, XDIM, YDIM)


        # ------------------------------------------------------------
        # if N-terminal bead (beadflag == 1)
        elif idx_to_bead[bead_index][0] == 1:
            anchor_bead = idx_to_bead[bead_index+1][5:7]

            new_position = single_bead_crank_2D(anchor_bead, grid, XDIM, YDIM)
            
            if hardwall == 1:
                two_position_holder[0] = new_position
                two_position_holder[1] = anchor_bead
                if do_positions_stradle_pbc_boundary_2D(two_position_holder, 2) == 1:
                    continue

        # ------------------------------------------------------------
        # if C-terminal bead (beadflag == 3)
        elif idx_to_bead[bead_index][0] == 3:

            anchor_bead = idx_to_bead[bead_index-1][5:7]
            new_position = single_bead_crank_2D(anchor_bead, grid, XDIM, YDIM)

            if hardwall == 1:
                two_position_holder[0] = anchor_bead
                two_position_holder[1] = new_position

                if do_positions_stradle_pbc_boundary_2D(two_position_holder,2) == 1:
                    continue

        # ------------------------------------------------------------
        # we're somewhere inside the chain, and beadflag is 2,4,5, or 6
        else:
            position_triptic[0] = idx_to_bead[bead_index-1][5:7]
            position_triptic[1] = idx_to_bead[bead_index][5:7]
            position_triptic[2] = idx_to_bead[bead_index+1][5:7]
        
            # normal crank move!
            new_position = crank_it_2D(position_triptic, grid, XDIM, YDIM)

            if hardwall == 1:
                three_position_holder[0] = position_triptic[0]
                three_position_holder[1] = new_position
                three_position_holder[2] = position_triptic[2]
                
                if do_positions_stradle_pbc_boundary_2D(three_position_holder,3) == 1:
                    continue
        
        # if hardsphere success
        if not new_position[0] < 0:
            
            delta_energy = get_energy_change_2D(grid, type_grid, old_position, new_position, idx_to_bead[bead_index][1],  interaction_table, LR_interaction_table, SLR_interaction_table, XDIM, YDIM, hardwall)
            print(delta_energy)

            delta_angle_energy = get_angle_energy_change_2D(bead_index, idx_to_bead, new_position, angle_lookup)
            
            if mega_crank.accept_or_reject_ext(invtemp, energy, energy+delta_energy+delta_angle_energy) == 1:
                                
                # delete from main grid and insert into new position                                            
                grid[old_position[0], old_position[1]] = 0

                # inert the bead to its new position
                grid[new_position[0], new_position[1]] = idx_to_bead[bead_index,4]
                
                # set new type grid to old type grid value
                type_grid[new_position[0], new_position[1]] = type_grid[old_position[0], old_position[1]]

                # zero out old position on type grid                
                type_grid[old_position[0], old_position[1]] = 0

                # IMPORTANT!!! This change *MUST* be done last as the old_position is actually a reference
                # to chain_position[bead_index] so changing it BEFORE hand changes the old_position variable and
                # breaks everything
                idx_to_bead[bead_index,5] = new_position[0]
                idx_to_bead[bead_index,6] = new_position[1]
                
                
                energy = energy + delta_energy + delta_angle_energy
                accepted_moves = accepted_moves + 1
                

    return (grid, type_grid, idx_to_bead, energy, accepted_moves)



# --------------------------------------------------------------------------------------------------------
#
# 
cdef crank_it_2D (cnp.ndarray[NUMPY_INT_TYPE, ndim=2] position_triptic, cnp.ndarray[NUMPY_INT_TYPE, ndim=2] grid, int XDIM, int YDIM):
    """
    Perform crankshaft move!

    Returns a tuple of success and the PBC corrected posistion

    """
   
    cdef int N_side_x, N_side_y, C_side_x, C_side_y;
    cdef int x_min, x_max, y_min, y_max
    cdef cnp.ndarray[NUMPY_INT_TYPE, ndim=1] new_position = np.zeros([2], dtype=int)
    
    # extract out x and y positions and perform a series of PBC corrections as needed
    N_side_x = position_triptic[0,0]
    N_side_y = position_triptic[0,1]

    C_side_x = position_triptic[2,0]
    C_side_y = position_triptic[2,1]

    ## Periodicity fix 1
    # move into a non-periodic space just for now
    if abs(N_side_x - C_side_x) > 2:
        if N_side_x > C_side_x:
            C_side_x = C_side_x + XDIM
        else:
            N_side_x = N_side_x + XDIM
        
    if abs(N_side_y - C_side_y) > 2:
        if N_side_y > C_side_y:
            C_side_y = C_side_y + YDIM
        else:
            N_side_y = N_side_y + YDIM

    # get smallest/largest possible new x value
    x_min = int_max(N_side_x-1, C_side_x-1) 
    x_max = int_min(N_side_x+1, C_side_x+1) 

    # get smallest/largest possible new y value
    y_min = int_max(N_side_y-1, C_side_y-1) 
    y_max = int_min(N_side_y+1, C_side_y+1) 
    
    cdef int local_x = pbc_correction((x_min + mega_crank.randint_ext(1, (x_max - x_min + 1)) - 1 ) , XDIM);
    cdef int local_y = pbc_correction((y_min + mega_crank.randint_ext(1, (y_max - y_min + 1)) - 1 ) , YDIM)
    
    if grid[local_x, local_y] > 0:
        # fail
        new_position[0] = -1
        return (new_position)

    # hard sphere clash
    else:
        # success        
        new_position[0] = local_x;
        new_position[1] = local_y;
        return (new_position)

# --------------------------------------------------------------------------------------------------------
#
# 
@cython.wraparound(False)
@cython.boundscheck(False)
cdef single_bead_crank_2D (cnp.ndarray[NUMPY_INT_TYPE, ndim=1] old_position, cnp.ndarray[NUMPY_INT_TYPE, ndim=2] grid, int XDIM, int YDIM):
    """
    Perform crankshaft move!

    Single beads are easy as the new position is just a random pertubation in all three coordinates

    """

    cdef cnp.ndarray[NUMPY_INT_TYPE, ndim=1] new_position = np.zeros([2], dtype=int)
    
    cdef int x_off, y_off;

    x_off = (mega_crank.randint_ext(0,2)-1)
    y_off = (mega_crank.randint_ext(0,2)-1)

    cdef int local_x = pbc_correction(old_position[0] + x_off, XDIM)
    cdef int local_y = pbc_correction(old_position[1] + y_off, YDIM)

    #if grid[new_position[0], new_position[1], new_position[2]] > 0:
    if grid[local_x, local_y] > 0:
        # fail
        new_position[0] = -1
        return (new_position)

    # hard sphere clash
    else:
        # success        
        new_position[0] = local_x
        new_position[1] = local_y
        return (new_position)


@cython.wraparound(False)
@cython.boundscheck(False)
cdef long get_angle_energy_change_2D(int bead_index,
                                     cnp.ndarray[NUMPY_INT_TYPE, ndim=2] idx_to_bead,
                                     cnp.ndarray[NUMPY_INT_TYPE, ndim=1] new_position, 
                                     cnp.ndarray[long, ndim=5] angle_lookup):
                        
    """
    Function that takes a pre-computed angle energy lookup table and returns the change
    in angle energy before and after the move, where the move must be moving a single bead. 
    Note this function is almost purely C (as measured by the output from cython -a)

    ## Parameters are as follows:

    bead_index
    Index position of the specific bead of interest
    
    idx_to_bead
    Full matrix containing the complete system information (see the description in
    the mega_crank function description for a full summary of this variable)

    new_position
    2D np.array ([x,y]) that defines the position that the moved bead 
    is moving to 

    angle_lookup
    5D lookup table that translates vector distances into an angle energy
    penalty based on precomputed values.

    """

    # if the skip angle is set to true
    if idx_to_bead[bead_index,3] == 1:
        return 0

    # initialize a bunch of values
    cdef cnp.ndarray[NUMPY_INT_TYPE, ndim=1] a = np.zeros([2], dtype=int)    
    cdef cnp.ndarray[NUMPY_INT_TYPE, ndim=1] b = np.zeros([2], dtype=int)    

    cdef long angle_penalty_new = 0;
    cdef long angle_penalty_old = 0;

    cdef cnp.ndarray[NUMPY_INT_TYPE, ndim=2] angle_positions  = np.zeros([5, 2], dtype=int)    
    cdef cnp.ndarray[NUMPY_INT_TYPE, ndim=1] intcode_lookup = np.zeros([5], dtype=int)    
    cdef int offset, offset_start, offset_end;
    cdef int i;
    cdef int angle_idx, local_move_idx;

    # N-terminal bead
    if idx_to_bead[bead_index,0] == 1:
        offset_start = 0
        offset_end   = 3

    # central bead
    elif idx_to_bead[bead_index,0] == 2:
        offset_start = -2
        offset_end   = 3

    # central bead in an OXO configuration
    elif idx_to_bead[bead_index,0] == 4:
        offset_start = -1
        offset_end   = 2


    # C terminal bead
    elif idx_to_bead[bead_index,0] == 3:
        offset_start = -2
        offset_end   = 1

    # N terminal bead +1 from start
    elif idx_to_bead[bead_index,0] == 5:
        offset_start = -1
        offset_end   = 3

    # C terminal bead -1 from end
    elif idx_to_bead[bead_index,0] == 6:
        offset_start = -2
        offset_end   = 2


    # this is the index we use to keep track of the dynamic angle_positions array
    angle_idx = 0

    local_move_idx  = -1
    angle_idx = 0

    for offset in range(offset_start, offset_end):
        pos = bead_index + offset

        angle_positions[angle_idx, 0] = idx_to_bead[pos,5] # x pos
        angle_positions[angle_idx, 1] = idx_to_bead[pos,6] # y pos
        intcode_lookup[angle_idx]     = idx_to_bead[pos,2] # intcode

        if pos == bead_index:
            local_move_idx = angle_idx

        angle_idx = angle_idx + 1


    for i in xrange(0, (angle_idx)-2):

        # compute the two vectors between the positions
        a[0] = fix_angle_pbc_issues(angle_positions[i+1, 0] - angle_positions[i, 0])
        a[1] = fix_angle_pbc_issues(angle_positions[i+1, 1] - angle_positions[i, 1])

        b[0] = fix_angle_pbc_issues(angle_positions[i+1, 0] - angle_positions[i+2, 0])
        b[1] = fix_angle_pbc_issues(angle_positions[i+1, 1] - angle_positions[i+2, 1])

        angle_penalty_old = angle_lookup[intcode_lookup[i+1], a[0]+1, a[1]+1, b[0]+1, b[1]+1] + angle_penalty_old

    angle_positions[local_move_idx,0] = new_position[0]
    angle_positions[local_move_idx,1] = new_position[1]

    for i in xrange(0, (angle_idx)-2):

        # compute the two vectors between the positions
        a[0] = fix_angle_pbc_issues(angle_positions[i+1, 0] - angle_positions[i, 0])
        a[1] = fix_angle_pbc_issues(angle_positions[i+1, 1] - angle_positions[i, 1])

        b[0] = fix_angle_pbc_issues(angle_positions[i+1, 0] - angle_positions[i+2, 0])
        b[1] = fix_angle_pbc_issues(angle_positions[i+1, 1] - angle_positions[i+2, 1])

        angle_penalty_new = angle_lookup[intcode_lookup[i+1], a[0]+1, a[1]+1, b[0]+1, b[1]+1] + angle_penalty_new
        
    return (angle_penalty_new - angle_penalty_old)    


@cython.cdivision(True)
cdef int fix_angle_pbc_issues(int distance):
    """
    Hack that takes advantage of the fact that the distances all must be -1,0, +1 and 
    we're always computing a X->O vector where O is the bend point

    """
    if distance < -1:
        return 1
    elif distance > 1:
        return -1
    else:
        return distance
    

# these directives made the function slower...
#@cython.wraparound(False)
#@cython.boundscheck(False)
def get_energy_change_2D(cnp.ndarray[NUMPY_INT_TYPE, ndim=2] grid, 
                         cnp.ndarray[NUMPY_INT_TYPE, ndim=2] type_grid,
                         cnp.ndarray[NUMPY_INT_TYPE, ndim=1] old_position,
                         cnp.ndarray[NUMPY_INT_TYPE, ndim=1] new_position,
                         int LR_vs_SR, 
                         cnp.ndarray[long, ndim=2] interaction_table, 
                         cnp.ndarray[long, ndim=2] LR_interaction_table,
                         cnp.ndarray[long, ndim=2] SLR_interaction_table,
                         int XDIM, 
                         int YDIM,
                         int hardwall):
                         

    # We define four energy variables which are going to be used to calcualte
    # the DELTA energy. 
    #
    # --> energy old is the interactions between the bead and its
    # partners in its current location
    #
    # --> energy_old_empy is the energy associated with the site after this
    # bead has been removed (i.e. solvent to local partners only)
    #
    # --> energy_new is the interaction between the bead and its partners in
    #     its NEW location!
    #
    # --> energy_new_empty is the interaction between the bead and its 
    
    cdef long energy_old       = 0
    cdef long energy_old_empty = 0
    cdef long energy_new       = 0
    cdef long energy_new_empty = 0 
    

    cdef int old_x, old_y;
    cdef int new_x, new_y;
    cdef int tmp_x, tmp_y;

    cdef int x, y

    cdef unsigned int site_bead_type, bead_type;

    # extract 
    new_x = new_position[0]
    new_y = new_position[1]

    old_x = old_position[0]
    old_y = old_position[1]

    # get the type of the current beads
    bead_type = type_grid[old_x, old_y]
    
    ## ************************************************************************************************
    ##  Long range energy
    ##
    # if we're looking at a bead which engages in longrange interactions 
    if LR_vs_SR == 1:

        ## First evaluate the old energy        
        for x in range(-3,4):
            for y in range(-3,4):
                tmp_x = pbc_correction(old_x + x, XDIM)
                tmp_y = pbc_correction(old_y + y, YDIM)

                site_bead_type = type_grid[tmp_x, tmp_y]

                # short-range interactions
                if abs(x) < 2 and abs(y) < 2:
                    
                    # if harwall boundary is on then short range interaction between a bead and something across
                    # the boundary is by definition bead-solvent interaction (type 0)
                    if hardwall == 1:
                        if abs(tmp_x - old_x) > 3 or abs(tmp_y - old_y) > 3:
                            site_bead_type = 0                
                        
                    # bead-site interaction                 
                    energy_old = energy_old + interaction_table[bead_type, site_bead_type]

                    # might be faster to just read this from memory every time - is if or a memory read and addition faster?
                    if site_bead_type > 0:
                        energy_old_empty = energy_old_empty + interaction_table[0, site_bead_type]

                # long range interactions (maybe optimize this in future...) - note long range interactions cannot
                # contribute to the energy_old_empty variable
                elif abs(x) < 3 and abs(y) < 3:                

                    # if harwall boundary is on - don't feel LR or SLR interactions over boundary
                    if hardwall == 1:
                        if abs(tmp_x - old_x) > 3 or abs(tmp_y - old_y) > 3:
                            continue
                    energy_old = energy_old + LR_interaction_table[bead_type, site_bead_type]

                else:
                    # if harwall boundary is on - don't feel LR or SLR interactions over boundary
                    if hardwall == 1:
                        if abs(tmp_x - old_x) > 3 or abs(tmp_y - old_y) > 3:
                            continue
                    energy_old = energy_old + SLR_interaction_table[bead_type, site_bead_type]
                    

        # reset the typegrid to the new configuation
        type_grid[new_x,new_y] = type_grid[old_x,old_y]
        type_grid[old_x,old_y] = 0

        ## then evaluate the new energy        
        for x in range(-3,4):
            for y in range(-3,4):

                # get PBC corrected positions of interest
                tmp_x = pbc_correction(new_x + x, XDIM)
                tmp_y = pbc_correction(new_y + y, YDIM)

                site_bead_type = type_grid[tmp_x, tmp_y]
                    
                # short-range interactions
                if abs(x) < 2 and abs(y) < 2:

                    if hardwall == 1:
                        if abs(tmp_x - new_x) > 3 or abs(tmp_y - new_y) > 3:
                            site_bead_type = 0                
                        
                    # bead-site interaction                 
                    energy_new = energy_new + interaction_table[bead_type, site_bead_type]
                    
                    if site_bead_type > 0:
                        energy_new_empty = energy_new_empty + interaction_table[0, site_bead_type]
                
                # long range interactions (maybe optimize this in future...) - note long range interactions cannot
                # contribute to the energy_old_empty variable

                # long range interactions (maybe optimize this in future...) - note long range interactions cannot
                # contribute to the energy_old_empty variable
                elif abs(x) < 3 and abs(y) < 3:              
                    # if harwall boundary is on - don't feel LR or SLR interactions over boundary
                    if hardwall == 1:
                        if abs(tmp_x - new_x) > 3 or abs(tmp_y - new_y) > 3:
                            continue  

                    energy_new = energy_new + LR_interaction_table[bead_type, site_bead_type]

                else:
                    # if harwall boundary is on - don't feel LR or SLR interactions over boundary
                    if hardwall == 1:
                        if abs(tmp_x - new_x) > 3 or abs(tmp_y - new_y) > 3:
                            continue  

                    energy_new = energy_new + SLR_interaction_table[bead_type, site_bead_type]


    ## ************************************************************************************************
    ##  only short range brah!
    ##
    else:
        for x in range(-1,2):
            for y in range(-1,2):

                # get PBC corrected positions of interest
                tmp_x = pbc_correction(old_x + x, XDIM)
                tmp_y = pbc_correction(old_y + y, YDIM)

                site_bead_type = type_grid[tmp_x, tmp_y]

                # if harwall boundary is on then overwrite site_bead_type
                if hardwall == 1:
                    if abs(tmp_x - old_x) > 3 or abs(tmp_y - old_y) > 3:
                        site_bead_type = 0                
                                                                 
                # bead-site interaction                 
                energy_old = energy_old + interaction_table[bead_type, site_bead_type]

                # might be faster to just read this from memory every time - is if or a memory read and addition faster?
                if site_bead_type > 0:
                    energy_old_empty = energy_old_empty + interaction_table[0, site_bead_type]
            
        # reset the typegrid to the new configuation
        type_grid[new_x,new_y] = type_grid[old_x,old_y]
        type_grid[old_x,old_y] = 0
                
        for x in range(-1,2):
            for y in range(-1,2):
                    
                # get PBC corrected positions of interest
                tmp_x = pbc_correction(new_x + x, XDIM)
                tmp_y = pbc_correction(new_y + y, YDIM)

                site_bead_type = type_grid[tmp_x, tmp_y]

                # if harwall boundary is on then overwrite site_bead_type
                if hardwall == 1:
                    if abs(tmp_x - new_x) > 3 or abs(tmp_y - new_y) > 3:
                        site_bead_type = 0                
                    
                # bead-site interaction                 
                energy_new = energy_new + interaction_table[bead_type, site_bead_type]

                # might be faster to just read this from memory every time - is if or a memory read and addition faster?
                if site_bead_type > 0:
                    energy_new_empty = energy_new_empty + interaction_table[0, site_bead_type]
                                                
    # finally correct for the self-self interactions we cover when x == y == 0
    energy_old_empty = energy_old_empty - interaction_table[0, bead_type]
    energy_old       = energy_old - interaction_table[bead_type, bead_type]
    energy_new_empty = energy_new_empty - interaction_table[0, bead_type]
    energy_new       = energy_new - interaction_table[bead_type, bead_type]

    # reset the type grid again...
    type_grid[old_x,old_y] = type_grid[new_x,new_y] 
    type_grid[new_x,new_y] = 0

    return (energy_new + energy_old_empty) - (energy_old + energy_new_empty)



@cython.cdivision(True)
cdef int pbc_correction(int value, int DIM):    
    """
    Performs intelligent periodic boundary correction
    which FIRST checks to see if we have a negative
    value and IF NOT uses the % operator - this means
    we can use % without checking the sign giving
    a 35% speedup per call
    """
                            
    if value < 0:
        return DIM+value
    else:
        return (value % DIM)


@cython.wraparound(False)
@cython.boundscheck(False)
cdef int do_positions_stradle_pbc_boundary_2D(cnp.ndarray[NUMPY_INT_TYPE, ndim=2] chain_positions, int chain_length):
    """                                       
    For a set of positions returns true if the positions straddle a boundary
    else return false

    """

    cdef int pidx
    cdef int p1_x, p2_x, p1_y, p2_y
    
    

    for pidx in range(0, chain_length-1):
        p1_x = chain_positions[pidx,0]
        p2_x = chain_positions[pidx+1,0]

        p1_y = chain_positions[pidx,1]
        p2_y = chain_positions[pidx+1,1]
        
        if abs(p1_x - p2_x) > 1:
            return 1

        if abs(p1_y - p2_y) > 1:
            return 1

    return 0

